# Warp Receiver Configuration
name: Warp Receiver
custom-model-data: 44405
lore:
  - An evolved Ender Receiver.
  - Can be paired to multiple senders.

# Use "ender-receiver" where you want that to be used.
# The default is the center of the 3x3 crafting grid
recipe:
  # Top Row
  item0: echo_shard
  item1: shulker_box
  item2: echo_shard

  # Middle Row
  item3: shulker_box
  item4: ender-receiver
  item5: shulker_box

  # Bottom Row
  item6: echo_shard
  item7: shulker_box
  item8: echo_shard